everblock_admin_configuration:
    path: /everblock/configuration
    methods: [GET]
    defaults:
        _controller: 'Everblock\\Tools\\Controller\\Admin\\ConfigurationController::index'
        _legacy_controller: 'AdminEverBlockConfiguration'
        _legacy_link: 'AdminEverBlockConfiguration'

everblock_admin_blocks:
    path: /everblock/blocks
    methods: [GET]
    defaults:
        _controller: 'Everblock\\Tools\\Controller\\Admin\\BlocksController::index'
        _legacy_controller: 'AdminEverBlock'
        _legacy_link: 'AdminEverBlock'

everblock_admin_hooks:
    path: /everblock/hooks
    methods: [GET]
    defaults:
        _controller: 'Everblock\\Tools\\Controller\\Admin\\HooksController::index'
        _legacy_controller: 'AdminEverBlockHook'
        _legacy_link: 'AdminEverBlockHook'

everblock_admin_shortcodes:
    path: /everblock/shortcodes
    methods: [GET]
    defaults:
        _controller: 'Everblock\\Tools\\Controller\\Admin\\ShortcodesController::index'
        _legacy_controller: 'AdminEverBlockShortcode'
        _legacy_link: 'AdminEverBlockShortcode'

everblock_admin_faq:
    path: /everblock/faq
    methods: [GET]
    defaults:
        _controller: 'Everblock\\Tools\\Controller\\Admin\\FaqController::index'
        _legacy_controller: 'AdminEverBlockFaq'
        _legacy_link: 'AdminEverBlockFaq'
