everblock_admin_configuration:
    path: /everblock/configuration
    methods: [GET]
    defaults:
        _controller: 'Everblock\\Tools\\Controller\\Admin\\ConfigurationController::index'
        _legacy_controller: 'AdminEverBlockConfiguration'
        _legacy_link: 'AdminEverBlockConfiguration'

everblock_admin_blocks:
    path: /everblock/blocks
    methods: [GET]
    defaults:
        _controller: 'Everblock\\Tools\\Controller\\Admin\\EverblockBlockController::index'
        _legacy_controller: 'AdminEverBlock'
        _legacy_link: 'AdminEverBlock'

everblock_admin_blocks_create:
    path: /everblock/blocks/new
    methods: [GET, POST]
    defaults:
        _controller: 'Everblock\\Tools\\Controller\\Admin\\EverblockBlockController::create'
        _legacy_controller: 'AdminEverBlock'
        _legacy_link: 'AdminEverBlock:add'

everblock_admin_blocks_edit:
    path: /everblock/blocks/{everblockId}/edit
    methods: [GET, POST]
    defaults:
        _controller: 'Everblock\\Tools\\Controller\\Admin\\EverblockBlockController::edit'
        _legacy_controller: 'AdminEverBlock'
        _legacy_link: 'AdminEverBlock:update'
    requirements:
        everblockId: "\\d+"

everblock_admin_blocks_duplicate:
    path: /everblock/blocks/{everblockId}/duplicate
    methods: [GET]
    defaults:
        _controller: 'Everblock\\Tools\\Controller\\Admin\\EverblockBlockController::duplicate'
        _legacy_controller: 'AdminEverBlock'
        _legacy_link: 'AdminEverBlock:duplicate'
    requirements:
        everblockId: "\\d+"

everblock_admin_blocks_toggle:
    path: /everblock/blocks/{everblockId}/toggle
    methods: [GET]
    defaults:
        _controller: 'Everblock\\Tools\\Controller\\Admin\\EverblockBlockController::toggle'
        _legacy_controller: 'AdminEverBlock'
        _legacy_link: 'AdminEverBlock:status'
    requirements:
        everblockId: "\\d+"

everblock_admin_blocks_bulk_delete:
    path: /everblock/blocks/bulk/delete
    methods: [POST]
    defaults:
        _controller: 'Everblock\\Tools\\Controller\\Admin\\EverblockBlockController::bulkDelete'
        _legacy_controller: 'AdminEverBlock'
        _legacy_link: 'AdminEverBlock:bulkdelete'

everblock_admin_blocks_bulk_duplicate:
    path: /everblock/blocks/bulk/duplicate
    methods: [POST]
    defaults:
        _controller: 'Everblock\\Tools\\Controller\\Admin\\EverblockBlockController::bulkDuplicate'
        _legacy_controller: 'AdminEverBlock'
        _legacy_link: 'AdminEverBlock:bulkduplicate'

everblock_admin_blocks_export:
    path: /everblock/blocks/{everblockId}/export
    methods: [GET]
    defaults:
        _controller: 'Everblock\\Tools\\Controller\\Admin\\EverblockBlockController::export'
        _legacy_controller: 'AdminEverBlock'
        _legacy_link: 'AdminEverBlock:export'
    requirements:
        everblockId: "\\d+"

everblock_admin_blocks_clear_cache:
    path: /everblock/blocks/cache/clear
    methods: [GET]
    defaults:
        _controller: 'Everblock\\Tools\\Controller\\Admin\\EverblockBlockController::clearCache'
        _legacy_controller: 'AdminEverBlock'
        _legacy_link: 'AdminEverBlock:clearcache'

everblock_admin_hooks:
    path: /everblock/hooks
    methods: [GET]
    defaults:
        _controller: 'Everblock\\Tools\\Controller\\Admin\\EverblockHookController::index'
        _legacy_controller: 'AdminEverBlockHook'
        _legacy_link: 'AdminEverBlockHook'

everblock_admin_hooks_create:
    path: /everblock/hooks/new
    methods: [GET, POST]
    defaults:
        _controller: 'Everblock\\Tools\\Controller\\Admin\\EverblockHookController::create'
        _legacy_controller: 'AdminEverBlockHook'
        _legacy_link: 'AdminEverBlockHook:add'

everblock_admin_hooks_edit:
    path: /everblock/hooks/{hookId}/edit
    methods: [GET, POST]
    defaults:
        _controller: 'Everblock\\Tools\\Controller\\Admin\\EverblockHookController::edit'
        _legacy_controller: 'AdminEverBlockHook'
        _legacy_link: 'AdminEverBlockHook:update'
    requirements:
        hookId: "\\d+"

everblock_admin_hooks_toggle:
    path: /everblock/hooks/{hookId}/toggle
    methods: [GET]
    defaults:
        _controller: 'Everblock\\Tools\\Controller\\Admin\\EverblockHookController::toggle'
        _legacy_controller: 'AdminEverBlockHook'
        _legacy_link: 'AdminEverBlockHook:status'
    requirements:
        hookId: "\\d+"

everblock_admin_hooks_bulk_enable:
    path: /everblock/hooks/bulk/enable
    methods: [POST]
    defaults:
        _controller: 'Everblock\\Tools\\Controller\\Admin\\EverblockHookController::bulkEnable'
        _legacy_controller: 'AdminEverBlockHook'
        _legacy_link: 'AdminEverBlockHook:bulkenable'

everblock_admin_hooks_bulk_disable:
    path: /everblock/hooks/bulk/disable
    methods: [POST]
    defaults:
        _controller: 'Everblock\\Tools\\Controller\\Admin\\EverblockHookController::bulkDisable'
        _legacy_controller: 'AdminEverBlockHook'
        _legacy_link: 'AdminEverBlockHook:bulkdisable'

everblock_admin_hooks_bulk_delete:
    path: /everblock/hooks/bulk/delete
    methods: [POST]
    defaults:
        _controller: 'Everblock\\Tools\\Controller\\Admin\\EverblockHookController::bulkDelete'
        _legacy_controller: 'AdminEverBlockHook'
        _legacy_link: 'AdminEverBlockHook:bulkdelete'

everblock_admin_shortcodes:
    path: /everblock/shortcodes
    methods: [GET]
    defaults:
        _controller: 'Everblock\\Tools\\Controller\\Admin\\ShortcodesController::index'
        _legacy_controller: 'AdminEverBlockShortcode'
        _legacy_link: 'AdminEverBlockShortcode'

everblock_admin_faq:
    path: /everblock/faq
    methods: [GET]
    defaults:
        _controller: 'Everblock\\Tools\\Controller\\Admin\\FaqController::index'
        _legacy_controller: 'AdminEverBlockFaq'
        _legacy_link: 'AdminEverBlockFaq'
