{*
 * 2019-2025 Team Ever
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@prestashop.com so we can send you a copy immediately.
 *
 *  @author    Team Ever <https://www.team-ever.com/>
 *  @copyright 2019-2025 Team Ever
 *  @license   http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
*}

<div class="card everblock-doc mt-3">
    <div class="card-body">
        <h3 class="card-title">
            <i class="icon-time"></i>
            {l s='Cron automation' mod='everblock'}
        </h3>
        <p>{l s='Copy the secure URLs generated by the module to schedule automated tasks on your server.' mod='everblock'}</p>
        <ul>
            <li>{l s='Each action uses a token that prevents unauthorised execution. Keep it private.' mod='everblock'}</li>
            <li>{l s='Trigger the links with wget or curl from your cron manager to refresh caches or feeds.' mod='everblock'}</li>
            <li>{l s='You can regenerate the token by saving the configuration if you suspect it has leaked.' mod='everblock'}</li>
        </ul>
    </div>
</div>
