name: PHP CS Fixer

on:
  push:
  pull_request:

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
      - name: Download PHP CS Fixer
        run: |
          curl -LsS https://cs.symfony.com/download/php-cs-fixer-v3.phar -o php-cs-fixer.phar
          php php-cs-fixer.phar --version
      - name: Run PHP CS Fixer
        run: |
          php php-cs-fixer.phar fix --dry-run --diff --config=.php-cs-fixer.php
