name: PHP Syntax Check

on:
  push:
    paths:
      - '**.php'
      - '**.tpl'
    paths-ignore:
      - 'vendor/**'
  pull_request:
    paths:
      - '**.php'
      - '**.tpl'
    paths-ignore:
      - 'vendor/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
      - name: Install Smarty
        run: composer global require smarty/smarty:^3
      - name: PHP lint
        run: |
          # Ignore vendor directory to avoid linting third-party code
          find . -path ./vendor -prune -o -name '*.php' -print0 | xargs -0 -n1 -I{} php -l {}
      - name: Smarty lint
        run: |
          files=$(find . -path ./vendor -prune -o -name '*.tpl' -print)
          if [ -n "$files" ]; then
            for f in $files; do
              php -r "require '$(composer global config home)/vendor/autoload.php'; \$smarty=new Smarty(); \$smarty->compileCheck=true; try{ \$smarty->fetch('$f'); } catch(Exception \$e){ echo \$e->getMessage(); exit(1);}"
            done
          fi
